name: ClearChat
main: me.DJBiokinetix.Main
author: DJBiokinetix
version: 1.2
website: http://www.spigotmc.org/resources/clearchat.1362/
description: Clear the chat!
commands:
   cc:
    description: Clear the chat
    aliases: [clearchat, cchat, clchat]
permissions:
    cc.clear:
        default: op
    cc.reload:
        default: op
    cc.lines:
        default: op
    cc.updates:
        default: op
    cc.personal:
        default: op